-- MySQL Script generated by MySQL Workbench
-- Fri Oct 15 12:00:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema career
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `career` ;

-- -----------------------------------------------------
-- Schema career
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `career` DEFAULT CHARACTER SET utf8 ;
USE `career` ;

-- -----------------------------------------------------
-- Table `career`.`position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `career`.`position` ;

CREATE TABLE IF NOT EXISTS `career`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lat` FLOAT NULL,
  `long` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `career`.`career`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `career`.`career` ;

CREATE TABLE IF NOT EXISTS `career`.`career` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `position_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_career_position1_idx` (`position_id` ASC) VISIBLE,
  CONSTRAINT `fk_career_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `career`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `career`.`transport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `career`.`transport` ;

CREATE TABLE IF NOT EXISTS `career`.`transport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NULL,
  `transportcol` VARCHAR(45) NULL,
  `career_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transport_career1_idx` (`career_id` ASC) VISIBLE,
  CONSTRAINT `fk_transport_career1`
    FOREIGN KEY (`career_id`)
    REFERENCES `career`.`career` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `career`.`worker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `career`.`worker` ;

CREATE TABLE IF NOT EXISTS `career`.`worker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transport_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_worker_transport1_idx` (`transport_id` ASC) VISIBLE,
  CONSTRAINT `fk_worker_transport1`
    FOREIGN KEY (`transport_id`)
    REFERENCES `career`.`transport` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `career`.`medic_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `career`.`medic_status` ;

CREATE TABLE IF NOT EXISTS `career`.`medic_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `temperature` FLOAT NULL,
  `worker_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medic_status_worker_idx` (`worker_id` ASC) VISIBLE,
  CONSTRAINT `fk_medic_status_worker`
    FOREIGN KEY (`worker_id`)
    REFERENCES `career`.`worker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `career`.`sensors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `career`.`sensors` ;

CREATE TABLE IF NOT EXISTS `career`.`sensors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transport_id` INT NOT NULL,
  `date_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sensors_transport1_idx` (`transport_id` ASC) VISIBLE,
  CONSTRAINT `fk_sensors_transport1`
    FOREIGN KEY (`transport_id`)
    REFERENCES `career`.`transport` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `career`.`worker_sensors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `career`.`worker_sensors` ;

CREATE TABLE IF NOT EXISTS `career`.`worker_sensors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `temperature` FLOAT NULL,
  `palpitation` FLOAT NULL,
  `sensors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_worker_sensors_sensors1_idx` (`sensors_id` ASC) VISIBLE,
  CONSTRAINT `fk_worker_sensors_sensors1`
    FOREIGN KEY (`sensors_id`)
    REFERENCES `career`.`sensors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `career`.`transport_sesnsors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `career`.`transport_sesnsors` ;

CREATE TABLE IF NOT EXISTS `career`.`transport_sesnsors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `speed` FLOAT NULL,
  `amount_of_gasoline` FLOAT NULL,
  `position_id` INT NOT NULL,
  `sensors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transport_sesnsors_position1_idx` (`position_id` ASC) VISIBLE,
  INDEX `fk_transport_sesnsors_sensors1_idx` (`sensors_id` ASC) VISIBLE,
  CONSTRAINT `fk_transport_sesnsors_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `career`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transport_sesnsors_sensors1`
    FOREIGN KEY (`sensors_id`)
    REFERENCES `career`.`sensors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `career`.`worker_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `career`.`worker_info` ;

CREATE TABLE IF NOT EXISTS `career`.`worker_info` (
  `worker_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birhday` DATE NOT NULL,
  CONSTRAINT `fk_worker_info_worker1`
    FOREIGN KEY (`worker_id`)
    REFERENCES `career`.`worker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `career`.`medical_insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `career`.`medical_insurance` ;

CREATE TABLE IF NOT EXISTS `career`.`medical_insurance` (
  `medic_id` INT NOT NULL,
  `medic_code` VARCHAR(45) NULL,
  INDEX `fk_medical_insurance_medic_status1_idx` (`medic_id` ASC) VISIBLE,
  CONSTRAINT `fk_medical_insurance_medic_status1`
    FOREIGN KEY (`medic_id`)
    REFERENCES `career`.`medic_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
